title: Shared AI Tech
description: A collection of shared tech ideas and blog posts
baseurl: "/shared-ai-tech" # ← IMPORTANT
url: "https://nguyenthuctrongnhan.github.io"

theme: minima

# Optional but helpful:
markdown: kramdown
permalink: pretty